"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import MenuBar from "@/components/MenuBar";
import Footerbar from "@/components/FooterBar";
import { AnimatePresence } from "framer-motion";
import AuthModal from "@/components/modals/Auth.component";
import { PageWrapper } from "@/components/WraperPage";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <MenuBar />
        <AuthModal />
        <AnimatePresence mode='wait'>{children}</AnimatePresence>
        <Footerbar />
      </body>
    </html>
  );
}
