import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import MenuBar from "@/components/MenuBar";
import AuthModal from "@/components/modals/Auth.component";
import FooterBar from "@/components/FooterBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <MenuBar />
        <AuthModal />
        {children}
        <FooterBar />
      </body>
    </html>
  );
}
